### ISSUE TITLE
Container interface

### ISSUE THREAD

**Issue by timiTao** [FriendsOfBehat/CrossContainerExtension#10]
Do you plan work your extension for container with Interop\Container\ContainerInterface?

I want simply use multi containers, but looking at youryour code, only symfony will work?

**Comment by pamil** [comment]
@timiTao sorry for such a delay, just got back to @FriendsOfBehat maintenance. As cross container is just a bunch of Symfony DI magic bundled together, I think it's rather impossible (or really difficult) to support other containers.
