### ISSUE TITLE
Escaped yaml parameters are not copied correctly

### ISSUE THREAD

**Issue by cdaguerre** [FriendsOfBehat/CrossContainerExtension#6]
[Copying parameters](https://github.com/FriendsOfBehat/CrossContainerExtension/blob/master/src/CrossContainerProcessor.php#L173) from one container to another doesn't work because you don't know whether parameters need to be escaped or not.
If the container has a parameter like: 
```
parameters:
  assets.version_format: %%s?%%s
```
This yaml is unescaped and resolved to `%s?%s` in the first container. 
When copied to the second container, you get a `ParameterNotFoundException` because the parameter `s?` is not found during compilation.

I've tried to find a workaround but I don't think there is a reliable way to figure out if a parameter should be escaped when copying it... Do you have an idea?
Maybe parameter copying should be configurable to allow reloading from source yaml files...

**Comment by pamil** [comment]
Thanks for reporting, fixed! 🎉

**Comment by pamil** [comment]
Tagged `v0.2.1`.

**Comment by cdaguerre** [comment]
Wow thanks :+1:
